/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/landscapes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Landscapes */
        get: operations["list_landscapes_v1_landscapes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/landscapes/{landscape_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Landscape */
        get: operations["get_landscape_v1_landscapes__landscape_id__get"];
        put?: never;
        post?: never;
        /** Delete Landscape Endpoint */
        delete: operations["delete_landscape_endpoint_v1_landscapes__landscape_id__delete"];
        options?: never;
        head?: never;
        /** Patch Landscape */
        patch: operations["patch_landscape_v1_landscapes__landscape_id__patch"];
        trace?: never;
    };
    "/v1/landscapes/{landscape_id}/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_v1_landscapes__landscape_id__papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/landscapes/{landscape_id}/expand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expand Landscape */
        post: operations["expand_landscape_v1_landscapes__landscape_id__expand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/landscapes/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream Landscape
         * @description Stream a landscape build as SSE frames.
         */
        post: operations["stream_landscape_v1_landscapes_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/landscapes/{landscape_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Replay the events for one landscape run.
         */
        get: operations["list_runs_v1_landscapes__landscape_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClusterOut */
        ClusterOut: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Paper Count
             * @default 0
             */
            paper_count: number;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Color
             * @default #94a3b8
             */
            color: string;
            /**
             * Is Unclustered
             * @default false
             */
            is_unclustered: boolean;
        };
        /** EdgeOut */
        EdgeOut: {
            /** Src Paper Id */
            src_paper_id: string;
            /** Dst Paper Id */
            dst_paper_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "extends" | "contradicts" | "applies" | "shares_method";
            /** Weight */
            weight: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Source
             * @default llm
             * @enum {string}
             */
            source: "knn" | "citation" | "llm";
            /** Confidence */
            confidence?: number | null;
        };
        /** ExpandRequest */
        ExpandRequest: {
            /**
             * Max New Results
             * @default 100
             */
            max_new_results: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LandscapeDetail */
        LandscapeDetail: {
            /** Id */
            id: number;
            /** Topic */
            topic: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "ready" | "failed";
            /**
             * Narrative Status
             * @default pending
             * @enum {string}
             */
            narrative_status: "pending" | "ok" | "partial" | "fallback" | "failed";
            /** Generation */
            generation: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Clusters */
            clusters?: components["schemas"]["ClusterOut"][];
            /** Papers */
            papers?: components["schemas"]["PaperInLandscape"][];
            /** Edges */
            edges?: components["schemas"]["EdgeOut"][];
            /** Tensions */
            tensions?: components["schemas"]["TensionOut"][];
            /** Open Problems */
            open_problems?: components["schemas"]["OpenProblemOut"][];
            /** Reading Path */
            reading_path?: components["schemas"]["ReadingStepOut"][];
        };
        /** LandscapeSummary */
        LandscapeSummary: {
            /** Id */
            id: number;
            /** Topic */
            topic: string;
            /** Title */
            title: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "ready" | "failed";
            /**
             * Narrative Status
             * @default pending
             * @enum {string}
             */
            narrative_status: "pending" | "ok" | "partial" | "fallback" | "failed";
            /** Generation */
            generation: number;
            /** Paper Count */
            paper_count: number;
            /** Cluster Count */
            cluster_count: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** OpenProblemOut */
        OpenProblemOut: {
            /** Statement */
            statement: string;
            /**
             * Why Open
             * @default
             */
            why_open: string;
            /** Supporting Paper Ids */
            supporting_paper_ids?: string[];
        };
        /**
         * PaperExtraction
         * @description Structured reading of one abstract (or, in v3, of full-text sections).
         *
         *     ``evidence`` must contain a verbatim span of the supplied text for each
         *     populated claim field — use ``evidence_violations`` (below) to check; the
         *     extraction pipeline refuses to store a field whose span is not a verbatim
         *     substring (§12.2 layer 3). A failed extraction is still a first-class row:
         *     ``status='failed'`` with ``error`` saying why, so nothing is silently lost
         *     (D3).
         */
        PaperExtraction: {
            /** Problem */
            problem?: string | null;
            /** Method */
            method?: string | null;
            /** Results */
            results?: string | null;
            /** Contribution */
            contribution?: string | null;
            /** Limitations */
            limitations?: string | null;
            /**
             * Novelty
             * @default unclear
             * @enum {string}
             */
            novelty: "incremental" | "substantial" | "unclear";
            /** Evidence */
            evidence?: {
                [key: string]: string;
            };
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "failed";
            /**
             * Error
             * @default
             */
            error: string;
        };
        /** PaperInLandscape */
        PaperInLandscape: {
            /** Paper Id */
            paper_id: string;
            /**
             * Version
             * @default
             */
            version: string;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string;
            /** Authors */
            authors?: string[];
            /**
             * Published
             * @default
             */
            published: string;
            /**
             * Updated
             * @default
             */
            updated: string;
            /**
             * Primary Category
             * @default
             */
            primary_category: string;
            /** Categories */
            categories?: string[];
            /**
             * Comment
             * @default
             */
            comment: string;
            /**
             * Journal Ref
             * @default
             */
            journal_ref: string;
            /**
             * Doi
             * @default
             */
            doi: string;
            /** Abs Url */
            abs_url: string;
            /**
             * Pdf Url
             * @default
             */
            pdf_url: string;
            /** Citation Count */
            citation_count?: number | null;
            /**
             * Citation Source
             * @default
             */
            citation_source: string;
            /**
             * Openalex Id
             * @default
             */
            openalex_id: string;
            /**
             * S2 Paper Id
             * @default
             */
            s2_paper_id: string;
            /**
             * Fulltext Status
             * @default none
             */
            fulltext_status: string;
            /** Rank */
            rank: number;
            /** Relevance Score */
            relevance_score: number;
            /** Cross Encoder Logit */
            cross_encoder_logit?: number | null;
            /** Relative Score */
            relative_score?: number | null;
            /** Rerank Source */
            rerank_source: string;
            /** Cluster Id */
            cluster_id?: number | null;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /**
             * Is Seed
             * @default false
             */
            is_seed: boolean;
            extraction?: components["schemas"]["PaperExtraction"] | null;
            /**
             * Extraction Status
             * @default ok
             * @enum {string}
             */
            extraction_status: "ok" | "failed";
        };
        /** ReadingStepOut */
        ReadingStepOut: {
            /** Paper Id */
            paper_id: string;
            /** Position */
            position: number;
            /**
             * Why
             * @default
             */
            why: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** TensionOut */
        TensionOut: {
            /** Statement */
            statement: string;
            /** Paper A Id */
            paper_a_id: string;
            /** Paper B Id */
            paper_b_id: string;
        };
        /** TopicRequest */
        TopicRequest: {
            /** Topic */
            topic: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_landscapes_v1_landscapes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandscapeSummary"][];
                };
            };
        };
    };
    get_landscape_v1_landscapes__landscape_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                landscape_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandscapeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_landscape_endpoint_v1_landscapes__landscape_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                landscape_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_landscape_v1_landscapes__landscape_id__patch: {
        parameters: {
            query?: {
                status?: ("running" | "ready" | "failed") | null;
                narrative_status?: ("pending" | "ok" | "partial" | "fallback" | "failed") | null;
                summary?: string | null;
            };
            header?: never;
            path: {
                landscape_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_v1_landscapes__landscape_id__papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                landscape_id: number;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperInLandscape"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expand_landscape_v1_landscapes__landscape_id__expand_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                landscape_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_landscape_v1_landscapes_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_v1_landscapes__landscape_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                landscape_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
